
package hangman.Panels;
import hangman.References.Names;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.BufferedReader;

/**
 * The EndPanel class creates a panel 
 * that is to be displayed immediately 
 * after a game of hangman is completed. 
 * The EndPanel always follows after a 
 * GamePanel. 
 */
public class EndPanel extends javax.swing.JPanel 
                      implements ActionListener{
    private CardLayout cardLayout;
    private JPanel deck;

    /**
     * Creates new form endPanel
     */
    public EndPanel() {
        initComponents();
        setScore();
        endButton.addActionListener(this);
    }
    
    public void actionPerformed(ActionEvent ae){
        wordLabel.setText("");
        cardLayout.show(deck, Names.MENU_PANEL);
    }
    
    public void setCardLayout(CardLayout cLayout, JPanel cards){
        cardLayout = cLayout;
        deck = cards;
    }
    
    public JLabel getScoreLabel(){
        return userScoreLabel;
    }
    
    public JLabel getWordLabel(){
        return wordLabel;
    }
    
    private void setScore(){
        try{
            File scoreFile = new File("score.txt");
            FileReader fileReader = new FileReader(scoreFile);
            BufferedReader scoreReader = new BufferedReader(fileReader);
            userScoreLabel.setText(scoreReader.readLine());
            repaint();
            revalidate();
        }
        catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userScoreLabel = new javax.swing.JLabel();
        endButton = new javax.swing.JButton();
        wordLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 51, 0));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setText("Game over");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setText("Score:");

        userScoreLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        userScoreLabel.setText("0");

        endButton.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        endButton.setText("End Game");

        wordLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userScoreLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(endButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userScoreLabel))
                .addGap(18, 18, 18)
                .addComponent(endButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(wordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel userScoreLabel;
    private javax.swing.JLabel wordLabel;
    // End of variables declaration//GEN-END:variables
}
